---
replicaCount: 2

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
    ephemeral-storage: "128Mi"
  limits:
    cpu: "100m"
    memory: "128Mi"
    ephemeral-storage: "128Mi"

persistence:
  universe:
    enabled: true
  logs:
    enabled: true

ingress:
  enabled: true

networkPolicy:
  enabled: true

serviceAccount:
  enabled: true

service:
  enableAdditionalHeadlessService: true
...
